name: Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # Frontend build
      - name: Frontend build
        working-directory: frontend
        run: |
          npm ci
          npm run build

      # Backend install (no tests yet)
      - name: Backend install
        working-directory: backend
        run: |
          npm ci
